# Generated by Django 6.0.2 on 2026-02-26 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wazuh_id', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('agent_name', models.CharField(max_length=200)),
                ('agent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('rule_id', models.CharField(max_length=20)),
                ('rule_level', models.IntegerField()),
                ('rule_description', models.TextField()),
                ('rule_groups', models.JSONField(default=list)),
                ('mitre_id', models.CharField(blank=True, max_length=50)),
                ('src_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info')], max_length=10)),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='alerts_aler_timesta_0459bf_idx'), models.Index(fields=['severity'], name='alerts_aler_severit_202179_idx'), models.Index(fields=['agent_name'], name='alerts_aler_agent_n_39f3ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(max_length=200)),
                ('mitre_technique', models.CharField(blank=True, max_length=50)),
                ('severity_assessment', models.CharField(max_length=20)),
                ('impact', models.TextField()),
                ('recommendations', models.TextField()),
                ('false_positive_pct', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('raw_response', models.TextField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='alerts.alert')),
            ],
        ),
    ]
