# Generated by Django 6.0.2 on 2026-03-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='remediation_steps',
            field=models.TextField(blank=True, default=''),
        ),
    ]
