# Generated by Django 6.0.2 on 2026-03-01 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_add_remediation_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('is_malicious', models.CharField(blank=True, max_length=50)),
                ('root_cause', models.TextField(blank=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('should_create_incident', models.BooleanField(default=False)),
                ('raw_response', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_chat', to='alerts.alert')),
            ],
        ),
    ]
