# Generated by Django 6.0.2 on 2026-03-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_add_ai_analysis_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysischat',
            name='recommended_action_th',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aianalysischat',
            name='root_cause_th',
            field=models.TextField(blank=True),
        ),
    ]
