# Generated by Django 6.0.2 on 2026-03-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_add_chat_bilingual'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='attack_type_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='impact_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='recommendations_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='remediation_steps_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='summary_en',
            field=models.TextField(blank=True, default=''),
        ),
    ]
