# Generated by Django 6.0.2 on 2026-03-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_bilingual_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
