# Generated by Django 5.2.12 on 2026-03-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_machine_type_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='agent_name',
            field=models.CharField(blank=True, help_text='ชื่อ agent ใน Wazuh', max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='department',
            field=models.CharField(blank=True, help_text='แผนก / หน่วยงาน', max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='hostname',
            field=models.CharField(blank=True, help_text='Hostname จริงของเครื่อง', max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, help_text='ห้อง / อาคาร / ชั้น', max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='owner',
            field=models.CharField(blank=True, help_text='ผู้ดูแล/เจ้าของเครื่อง', max_length=200),
        ),
    ]
