#!/usr/bin/env bash
# =============================================================================
# SOC Dashboard — Docker Init Script
# สร้าง .env อัตโนมัติ แล้วรัน docker compose up
#
# วิธีใช้:
#   sudo bash scripts/init.sh
# =============================================================================
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BLUE='\033[0;34m'; NC='\033[0m'
ok()   { echo -e "${GREEN}[OK]${NC} $*"; }
info() { echo -e "${CYAN}[INFO]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()  { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$APP_DIR"

echo -e "${BLUE}════════════════════════════════════════════${NC}"
echo -e "${BLUE}  SOC Dashboard — Setup${NC}"
echo -e "${BLUE}════════════════════════════════════════════${NC}"
echo ""

# ── ตรวจสอบ .env ─────────────────────────────────────────────────────────────
if [[ -f .env ]]; then
    warn ".env มีอยู่แล้ว — ข้ามการสร้างใหม่"
    warn "ถ้าต้องการ reset ให้ลบ .env ก่อน: rm .env"
    echo ""
else
    # ── Auto-detect server IP ─────────────────────────────────────────────────
    SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}')
    if [[ -z "$SERVER_IP" ]]; then
        SERVER_IP=$(ip route get 1.1.1.1 2>/dev/null | awk '/src/{print $7}' | head -1)
    fi
    [[ -z "$SERVER_IP" ]] && SERVER_IP="localhost"
    info "ตรวจพบ IP เครื่อง: ${SERVER_IP}"

    # ── ถามแค่ Port ───────────────────────────────────────────────────────────
    # Wazuh URL และ Password ตั้งค่าได้ภายหลังที่ /settings/ หลัง login
    echo ""
    read -rp "  Dashboard Port [8500]: " DASH_PORT
    DASH_PORT="${DASH_PORT:-8500}"

    # Wazuh — ค่า placeholder, ตั้งค่าจริงได้ที่ /settings/ หลัง login
    WAZUH_URL="https://127.0.0.1:9200"
    WAZUH_PASS=""

    # ── Auto-generate secrets ─────────────────────────────────────────────────
    SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(50))")
    DB_PASS=$(python3 -c "import secrets; print(secrets.token_hex(16))")
    # LICENSE_VENDOR_SECRET คงที่ต่อ vendor (เปลี่ยนก่อน distribute)
    LICENSE_SECRET="7f99cb03c61a21d1479eb80682e0aaf08d5b4dfeb043a500d0d5951aca090c01"

    # ── สร้าง .env ────────────────────────────────────────────────────────────
    cat > .env << EOF
# SOC Dashboard — Auto-generated by init.sh
# $(date '+%Y-%m-%d %H:%M:%S')

SECRET_KEY=${SECRET_KEY}
DEBUG=False
ALLOWED_HOSTS=localhost,127.0.0.1,${SERVER_IP}
CSRF_TRUSTED_ORIGINS=http://${SERVER_IP}:${DASH_PORT}

DB_NAME=soc_db
DB_USER=soc_user
DB_PASSWORD=${DB_PASS}

REDIS_URL=redis://redis:6379/1

DJANGO_DASHBOARD_URL=http://${SERVER_IP}:${DASH_PORT}
DASHBOARD_PORT=${DASH_PORT}

SOC_BOT_API_TOKEN=

LICENSE_VENDOR_SECRET=${LICENSE_SECRET}
LICENSE_GRACE_DAYS=30

WAZUH_INDEXER_URL=${WAZUH_URL}
WAZUH_INDEXER_USERNAME=admin
WAZUH_INDEXER_PASSWORD=${WAZUH_PASS}
WAZUH_VULN_INDEX=wazuh-states-vulnerabilities-wazuh-server
EOF

    ok ".env สร้างเรียบร้อย"
fi

# ── ตรวจสอบ Docker ────────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
    err "ไม่พบ Docker — กรุณาติดตั้งก่อน: https://docs.docker.com/engine/install/"
fi
if ! docker compose version &>/dev/null; then
    err "ไม่พบ Docker Compose plugin — กรุณาติดตั้งก่อน"
fi

# ── Docker Compose Up ─────────────────────────────────────────────────────────
info "Starting Docker Compose stack..."
docker compose up -d

# ── รอให้ app พร้อม ───────────────────────────────────────────────────────────
info "รอให้ระบบพร้อม..."
for i in $(seq 1 30); do
    if docker compose exec -T app python manage.py check --deploy 2>/dev/null | grep -q "0 issues"; then
        break
    fi
    sleep 2
done

# ── Migrate ───────────────────────────────────────────────────────────────────
info "Running migrations..."
docker compose exec app python manage.py migrate --noinput
ok "Migration เสร็จสิ้น"

# ── Collectstatic ─────────────────────────────────────────────────────────────
info "Collecting static files..."
docker compose exec app python manage.py collectstatic --noinput
ok "Static files เสร็จสิ้น"

# ── สร้าง superuser ───────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}สร้าง Admin User:${NC}"
docker compose exec app python manage.py createsuperuser

# ── Done ──────────────────────────────────────────────────────────────────────
DASH_PORT=$(grep "DASHBOARD_PORT" .env | cut -d= -f2)
SERVER_IP=$(grep "ALLOWED_HOSTS" .env | cut -d= -f2 | tr ',' '\n' | grep -v localhost | grep -v "127.0.0.1" | head -1)

echo ""
echo -e "${GREEN}════════════════════════════════════════════${NC}"
echo -e "${GREEN}  ติดตั้งเสร็จสมบูรณ์!${NC}"
echo -e "${GREEN}════════════════════════════════════════════${NC}"
echo ""
echo -e "  เข้าใช้งาน: ${CYAN}http://${SERVER_IP}:${DASH_PORT}${NC}"
echo ""
echo -e "  ขั้นตอนถัดไป:"
echo -e "  1. เข้า ${CYAN}http://${SERVER_IP}:${DASH_PORT}/settings/${NC}"
echo -e "     → ตั้งค่า Wazuh Indexer URL และ Password"
echo -e "     → ตั้งค่า LINE, SMTP, TheHive และ integration อื่นๆ"
echo -e "  2. เข้า ${CYAN}http://${SERVER_IP}:${DASH_PORT}/settings/wazuh-check/${NC}"
echo -e "     → ตรวจสอบการเชื่อมต่อ Wazuh"
echo -e "  3. เข้า ${CYAN}http://${SERVER_IP}:${DASH_PORT}/license/${NC}"
echo -e "     → ใส่ License Key"
echo ""
