#!/usr/bin/env bash
# =============================================================================
# SOC Dashboard — Docker Init Script
# สร้าง .env อัตโนมัติ แล้วรัน docker compose up
#
# วิธีใช้:
#   sudo bash scripts/init.sh
# =============================================================================
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BLUE='\033[0;34m'; NC='\033[0m'
ok()   { echo -e "${GREEN}[OK]${NC} $*"; }
info() { echo -e "${CYAN}[INFO]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()  { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$APP_DIR"

echo -e "${BLUE}════════════════════════════════════════════${NC}"
echo -e "${BLUE}  SOC Dashboard — Setup${NC}"
echo -e "${BLUE}════════════════════════════════════════════${NC}"
echo ""

# ── ดึง code ล่าสุดจาก GitHub ────────────────────────────────────────────────
if git rev-parse --is-inside-work-tree &>/dev/null; then
    info "ดึง code ล่าสุดจาก GitHub..."
    git pull origin main 2>/dev/null && ok "Code อัปเดตแล้ว" || warn "git pull ไม่สำเร็จ — ใช้ code ปัจจุบัน"
fi

# ── ตรวจสอบ .env ─────────────────────────────────────────────────────────────
if [[ -f .env ]]; then
    warn ".env มีอยู่แล้ว — ข้ามการสร้างใหม่"
    warn "ถ้าต้องการ reset ให้ลบ .env ก่อน: rm .env"
    echo ""
else
    # ── Auto-detect server IP ─────────────────────────────────────────────────
    SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}')
    if [[ -z "$SERVER_IP" ]]; then
        SERVER_IP=$(ip route get 1.1.1.1 2>/dev/null | awk '/src/{print $7}' | head -1)
    fi
    [[ -z "$SERVER_IP" ]] && SERVER_IP="localhost"
    info "ตรวจพบ IP เครื่อง: ${SERVER_IP}"

    # ── ถามแค่ Port ───────────────────────────────────────────────────────────
    # Wazuh URL และ Password ตั้งค่าได้ภายหลังที่ /settings/ หลัง login
    echo ""
    read -rp "  Dashboard Port [8500]: " DASH_PORT
    DASH_PORT="${DASH_PORT:-8500}"

    # Wazuh — ค่า placeholder, ตั้งค่าจริงได้ที่ /settings/ หลัง login
    WAZUH_URL="https://127.0.0.1:9200"
    WAZUH_PASS=""

    # ── Auto-generate secrets ─────────────────────────────────────────────────
    SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(50))")
    DB_PASS=$(python3 -c "import secrets; print(secrets.token_hex(16))")
    # LICENSE_VENDOR_SECRET คงที่ต่อ vendor (เปลี่ยนก่อน distribute)
    LICENSE_SECRET="7f99cb03c61a21d1479eb80682e0aaf08d5b4dfeb043a500d0d5951aca090c01"

    # ── สร้าง .env ────────────────────────────────────────────────────────────
    cat > .env << EOF
# SOC Dashboard — Auto-generated by init.sh
# $(date '+%Y-%m-%d %H:%M:%S')

SECRET_KEY=${SECRET_KEY}
DEBUG=False
ALLOWED_HOSTS=localhost,127.0.0.1,${SERVER_IP}
CSRF_TRUSTED_ORIGINS=http://${SERVER_IP}:${DASH_PORT}

DB_NAME=soc_db
DB_USER=soc_user
DB_PASSWORD=${DB_PASS}

REDIS_URL=redis://redis:6379/1

DJANGO_DASHBOARD_URL=http://${SERVER_IP}:${DASH_PORT}
DASHBOARD_PORT=${DASH_PORT}

SOC_BOT_API_TOKEN=

LICENSE_VENDOR_SECRET=${LICENSE_SECRET}
LICENSE_GRACE_DAYS=30

WAZUH_INDEXER_URL=${WAZUH_URL}
WAZUH_INDEXER_USERNAME=admin
WAZUH_INDEXER_PASSWORD=${WAZUH_PASS}
WAZUH_VULN_INDEX=wazuh-states-vulnerabilities-wazuh-server
EOF

    ok ".env สร้างเรียบร้อย"
fi

# ── ตรวจสอบ OS ────────────────────────────────────────────────────────────────
_detect_os() {
    if [[ -f /etc/os-release ]]; then
        . /etc/os-release
        case "${ID,,}" in
            ubuntu|debian)           OS_TYPE="ubuntu" ;;
            almalinux|rhel|centos|rocky) OS_TYPE="almalinux" ;;
            *)                       OS_TYPE="unknown" ;;
        esac
        OS_NAME="${PRETTY_NAME:-$ID}"
    else
        OS_TYPE="unknown"
        OS_NAME="Unknown OS"
    fi
}

_detect_os
info "ตรวจพบ OS: ${OS_NAME}"

if [[ "$OS_TYPE" == "unknown" ]]; then
    warn "OS ไม่รองรับการติดตั้งอัตโนมัติ (รองรับ: Ubuntu, AlmaLinux/RHEL)"
fi

# ── ตรวจสอบและติดตั้ง Docker ─────────────────────────────────────────────────
_install_docker() {
    info "ติดตั้ง Docker..."
    if ! command -v curl &>/dev/null; then
        if [[ "$OS_TYPE" == "ubuntu" ]]; then
            apt-get update -qq && apt-get install -y curl
        elif [[ "$OS_TYPE" == "almalinux" ]]; then
            dnf install -y curl
        else
            err "ไม่พบ curl — กรุณาติดตั้งก่อน"
        fi
    fi

    if [[ "$OS_TYPE" == "ubuntu" ]]; then
        # Ubuntu: ติดตั้งผ่าน official Docker apt repo
        apt-get update -qq
        apt-get install -y ca-certificates curl gnupg
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
            | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
            > /etc/apt/sources.list.d/docker.list
        apt-get update -qq
        apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

    elif [[ "$OS_TYPE" == "almalinux" ]]; then
        # AlmaLinux/RHEL: ติดตั้งผ่าน official Docker dnf repo
        dnf install -y dnf-plugins-core
        dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
        dnf install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

    else
        # Fallback: convenience script
        curl -fsSL https://get.docker.com | sh
    fi

    systemctl enable --now docker
    ok "Docker ติดตั้งเสร็จสิ้น"
}

if ! command -v docker &>/dev/null; then
    warn "ไม่พบ Docker — จะติดตั้งอัตโนมัติ"
    read -rp "  ยืนยันติดตั้ง Docker? [Y/n]: " _ANS
    _ANS="${_ANS:-y}"
    if [[ "${_ANS,,}" == "y" ]]; then
        _install_docker
    else
        err "ต้องการ Docker เพื่อดำเนินการต่อ — https://docs.docker.com/engine/install/"
    fi
fi

_install_compose_plugin() {
    if [[ "$OS_TYPE" == "ubuntu" ]]; then
        # เพิ่ม Docker apt repo ก่อน (กรณี Docker ติดตั้งมาจากช่องทางอื่น)
        if [[ ! -f /etc/apt/keyrings/docker.gpg ]]; then
            info "เพิ่ม Docker apt repo..."
            apt-get install -y ca-certificates curl gnupg
            install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
                | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            chmod a+r /etc/apt/keyrings/docker.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
                > /etc/apt/sources.list.d/docker.list
            apt-get update -qq
        fi
        apt-get install -y docker-compose-plugin && return 0

    elif [[ "$OS_TYPE" == "almalinux" ]]; then
        if ! dnf repolist | grep -q docker-ce; then
            info "เพิ่ม Docker dnf repo..."
            dnf install -y dnf-plugins-core
            dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
        fi
        dnf install -y docker-compose-plugin && return 0
    fi

    # Fallback: download binary ตรง
    info "ติดตั้ง Docker Compose แบบ binary..."
    local COMPOSE_VERSION
    COMPOSE_VERSION=$(curl -fsSL https://api.github.com/repos/docker/compose/releases/latest \
        | grep '"tag_name"' | cut -d'"' -f4)
    local COMPOSE_URL="https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-linux-$(uname -m)"
    mkdir -p /usr/local/lib/docker/cli-plugins
    curl -fsSL "$COMPOSE_URL" -o /usr/local/lib/docker/cli-plugins/docker-compose
    chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
}

if ! docker compose version &>/dev/null 2>&1; then
    warn "ไม่พบ Docker Compose plugin — จะติดตั้งอัตโนมัติ"
    read -rp "  ยืนยันติดตั้ง? [Y/n]: " _ANS2
    _ANS2="${_ANS2:-y}"
    if [[ "${_ANS2,,}" == "y" ]]; then
        _install_compose_plugin
        if ! docker compose version &>/dev/null 2>&1; then
            err "ติดตั้ง Docker Compose ไม่สำเร็จ — https://docs.docker.com/compose/install/"
        fi
        ok "Docker Compose plugin ติดตั้งเสร็จสิ้น"
    else
        err "ต้องการ Docker Compose เพื่อดำเนินการต่อ"
    fi
fi

ok "Docker $(docker --version | awk '{print $3}' | tr -d ',')"
ok "Docker Compose $(docker compose version --short 2>/dev/null || echo 'OK')"

# ── ตรวจสอบ volume เก่า ──────────────────────────────────────────────────────
COMPOSE_PROJECT=$(basename "$APP_DIR" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]_-')
VOLUME_NAME="${COMPOSE_PROJECT}_postgres_data"
if docker volume inspect "$VOLUME_NAME" &>/dev/null; then
    warn "พบ postgres volume เก่า ($VOLUME_NAME)"
    warn "ถ้า password ใน .env ไม่ตรงกับ volume เก่า — migrate จะ fail"
    echo ""
    read -rp "  ลบ volume เก่าและเริ่มใหม่? (ข้อมูลใน DB จะหาย) [y/N]: " _VANS
    if [[ "${_VANS,,}" == "y" ]]; then
        docker compose down -v 2>/dev/null || true
        ok "ลบ volume เก่าแล้ว"
    else
        info "คงไว้ volume เดิม — ถ้า migrate fail ให้รัน: docker compose down -v"
    fi
fi

# ── ตั้งค่า Firewall ──────────────────────────────────────────────────────────
_DASH_PORT=$(grep "^DASHBOARD_PORT=" .env 2>/dev/null | cut -d= -f2-)
_DASH_PORT="${_DASH_PORT:-8500}"
_FW_PORTS=(22 "${_DASH_PORT}" 9000)   # SSH, Dashboard, TheHive

_setup_firewall() {
    if command -v ufw &>/dev/null; then
        # Ubuntu — ufw
        info "ตั้งค่า ufw firewall..."
        ufw --force reset >/dev/null
        ufw default deny incoming >/dev/null
        ufw default allow outgoing >/dev/null
        for _p in "${_FW_PORTS[@]}"; do
            ufw allow "${_p}/tcp" >/dev/null
            ok "ufw: allow ${_p}/tcp"
        done
        ufw --force enable >/dev/null
        ok "ufw เปิดใช้งานแล้ว"

    elif command -v firewall-cmd &>/dev/null; then
        # AlmaLinux — firewalld
        info "ตั้งค่า firewalld..."
        systemctl enable --now firewalld
        for _p in "${_FW_PORTS[@]}"; do
            firewall-cmd --permanent --add-port="${_p}/tcp" >/dev/null
            ok "firewalld: allow ${_p}/tcp"
        done
        firewall-cmd --reload >/dev/null
        ok "firewalld เปิดใช้งานแล้ว"

    else
        warn "ไม่พบ ufw หรือ firewalld — ข้ามการตั้งค่า firewall"
    fi
}

echo ""
read -rp "  เปิดใช้งาน Firewall และ allow port ${_DASH_PORT} (Dashboard), 9000 (TheHive), 22 (SSH)? [Y/n]: " _FANS
_FANS="${_FANS:-y}"
if [[ "${_FANS,,}" == "y" ]]; then
    _setup_firewall
fi

# ── Docker Compose Up ─────────────────────────────────────────────────────────
info "Starting Docker Compose stack..."
docker compose up -d

# ── รอให้ app พร้อม ───────────────────────────────────────────────────────────
info "รอให้ระบบพร้อม..."
for i in $(seq 1 30); do
    if docker compose exec -T app python manage.py check --deploy 2>/dev/null | grep -q "0 issues"; then
        break
    fi
    sleep 2
done

# ── Migrate ───────────────────────────────────────────────────────────────────
info "Running migrations..."
docker compose exec app python manage.py migrate --noinput
ok "Migration เสร็จสิ้น"

# ── Seed Wazuh Indexer URL จาก .env (เฉพาะครั้งแรก ถ้า DB ยังว่าง) ──────────
_ENV_WAZUH_URL=$(grep "^WAZUH_INDEXER_URL=" .env | cut -d= -f2-)
_ENV_WAZUH_USER=$(grep "^WAZUH_INDEXER_USERNAME=" .env | cut -d= -f2-)
if [[ -n "$_ENV_WAZUH_URL" ]]; then
docker compose exec -T app python manage.py shell -c "
from apps.config.models import IntegrationConfig
obj = IntegrationConfig.objects.filter(key='WAZUH_INDEXER_URL').first()
if not obj or not obj.value:
    IntegrationConfig.objects.filter(key='WAZUH_INDEXER_URL').update(value='${_ENV_WAZUH_URL}')
    IntegrationConfig.objects.filter(key='WAZUH_INDEXER_USER').update(value='${_ENV_WAZUH_USER:-admin}')
    print('seeded')
else:
    print('skip')
" 2>/dev/null | grep -q "seeded" && info "Wazuh Indexer URL seeded → ${_ENV_WAZUH_URL}" || true
fi

# ── Collectstatic ─────────────────────────────────────────────────────────────
info "Collecting static files..."
docker compose exec app python manage.py collectstatic --noinput
ok "Static files เสร็จสิ้น"

# ── สร้าง superuser (เฉพาะครั้งแรก) ─────────────────────────────────────────
_SU_EXISTS=$(docker compose exec -T app python manage.py shell -c \
    "from django.contrib.auth import get_user_model; print(get_user_model().objects.filter(is_superuser=True).exists())" \
    2>/dev/null | tr -d '[:space:]')
if [[ "$_SU_EXISTS" == "True" ]]; then
    warn "มี superuser อยู่แล้ว — ข้ามการสร้างใหม่"
else
    echo ""
    echo -e "${CYAN}สร้าง Admin User:${NC}"
    docker compose exec app python manage.py createsuperuser
fi

# ── ติดตั้ง Ollama (optional) ─────────────────────────────────────────────────
echo ""
read -rp "  ต้องการติดตั้ง Ollama (Local LLM สำหรับ AI Analysis)? [y/N]: " _OLANS
_OLANS="${_OLANS:-n}"
if [[ "${_OLANS,,}" == "y" ]]; then
    if command -v ollama &>/dev/null; then
        warn "Ollama ติดตั้งอยู่แล้ว ($(ollama --version 2>/dev/null || echo 'OK'))"
    else
        info "ติดตั้ง Ollama..."
        curl -fsSL https://ollama.com/install.sh | sh
        ok "Ollama ติดตั้งเสร็จสิ้น"
    fi

    # เปิด service
    systemctl enable --now ollama 2>/dev/null || true

    # ถามว่าจะ pull model ไหน
    echo ""
    read -rp "  Pull Ollama model (default: qwen2.5:7b, กด Enter เพื่อข้าม): " _OL_MODEL
    _OL_MODEL="${_OL_MODEL:-}"
    if [[ -n "$_OL_MODEL" ]]; then
        info "กำลัง pull ${_OL_MODEL} (อาจใช้เวลานาน)..."
        ollama pull "$_OL_MODEL" && ok "Pull ${_OL_MODEL} สำเร็จ"
    else
        warn "ข้าม — pull model ได้ภายหลัง: ollama pull qwen2.5:7b"
    fi
fi

# ── ติดตั้ง soc-bot service (ถ้ามี) ──────────────────────────────────────────
SOC_BOT_DIR="${APP_DIR}/soc-bot"
if [[ -f "${SOC_BOT_DIR}/main.py" ]]; then
    echo ""
    info "ตั้งค่า soc-bot service..."

    # สร้าง .env ของ soc-bot ถ้ายังไม่มี
    if [[ ! -f "${SOC_BOT_DIR}/.env" ]]; then
        cp "${SOC_BOT_DIR}/.env.example" "${SOC_BOT_DIR}/.env"
        ok "สร้าง soc-bot/.env จาก .env.example — กรุณาแก้ค่าก่อนใช้งาน"
    else
        warn "soc-bot/.env มีอยู่แล้ว — ข้ามการสร้างใหม่"
    fi

    # ติดตั้ง python3-venv ถ้าจำเป็น
    if ! python3 -c "import ensurepip" &>/dev/null; then
        info "ติดตั้ง python3-venv..."
        if [[ "$OS_TYPE" == "ubuntu" ]]; then
            PY_VER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
            apt-get install -y "python${PY_VER}-venv" 2>/dev/null || apt-get install -y python3-venv
        elif [[ "$OS_TYPE" == "almalinux" ]]; then
            dnf install -y python3-virtualenv 2>/dev/null || true
        fi
    fi

    # install venv ถ้ายังไม่มี
    if [[ ! -d "${SOC_BOT_DIR}/venv" ]]; then
        info "สร้าง soc-bot venv..."
        python3 -m venv "${SOC_BOT_DIR}/venv"
        "${SOC_BOT_DIR}/venv/bin/pip" install -q -r "${SOC_BOT_DIR}/requirements.txt"
        ok "soc-bot venv พร้อมแล้ว"
    fi

    # install systemd service พร้อม path จริง
    BOT_USER=$(whoami)
    sed -e "s|__SOC_BOT_USER__|${BOT_USER}|g" \
        -e "s|__SOC_BOT_DIR__|${SOC_BOT_DIR}|g" \
        "${SOC_BOT_DIR}/soc-bot.service" > /etc/systemd/system/soc-bot.service
    systemctl daemon-reload
    systemctl enable soc-bot 2>/dev/null || true
    ok "soc-bot.service ติดตั้งแล้ว (ยังไม่ start — แก้ .env ก่อน)"
    warn "กรุณาแก้ ${SOC_BOT_DIR}/.env แล้วรัน: sudo systemctl start soc-bot"
fi

# ── ติดตั้ง TheHive (optional) ────────────────────────────────────────────────
echo ""
read -rp "  ต้องการติดตั้ง TheHive 5 (Case Management)? [y/N]: " _THANS
_THANS="${_THANS:-n}"
if [[ "${_THANS,,}" == "y" ]]; then
    THEHIVE_COMPOSE="${APP_DIR}/docker-compose.thehive.yml"

    if [[ ! -f "$THEHIVE_COMPOSE" ]]; then
        err "ไม่พบ docker-compose.thehive.yml — กรุณา git pull ล่าสุด"
    fi

    # Generate secret ถ้ายังไม่มีใน .env
    if ! grep -q "^THEHIVE_SECRET=" .env 2>/dev/null; then
        _TH_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))")
        echo "THEHIVE_SECRET=${_TH_SECRET}" >> .env
        ok "สร้าง THEHIVE_SECRET แล้ว"
    else
        warn "THEHIVE_SECRET มีอยู่แล้วใน .env — ใช้ค่าเดิม"
    fi

    info "Starting TheHive + Cassandra..."
    docker compose -f "$THEHIVE_COMPOSE" --env-file .env up -d
    ok "TheHive containers started"

    info "รอให้ TheHive พร้อม (อาจใช้เวลา 2-3 นาที)..."
    _TH_READY=false
    for _i in $(seq 1 36); do
        if curl -sf "http://localhost:9000/api/status" &>/dev/null; then
            _TH_READY=true
            break
        fi
        sleep 5
    done

    if [[ "$_TH_READY" == "true" ]]; then
        ok "TheHive พร้อมใช้งานที่ http://localhost:9000"
        ok "Default login: admin@thehive.local / secret"
    else
        warn "TheHive ยังไม่พร้อม — รอ Cassandra initialize (ปกติใช้เวลา 3-5 นาทีครั้งแรก)"
        warn "ตรวจสอบ: docker compose -f docker-compose.thehive.yml logs -f thehive"
    fi
fi

# ── Done ──────────────────────────────────────────────────────────────────────
DASH_PORT=$(grep "DASHBOARD_PORT" .env | cut -d= -f2)
SERVER_IP=$(grep "ALLOWED_HOSTS" .env | cut -d= -f2 | tr ',' '\n' | grep -v localhost | grep -v "127.0.0.1" | head -1)

echo ""
echo -e "${GREEN}════════════════════════════════════════════${NC}"
echo -e "${GREEN}  ติดตั้งเสร็จสมบูรณ์!${NC}"
echo -e "${GREEN}════════════════════════════════════════════${NC}"
echo ""
echo -e "  เข้าใช้งาน: ${CYAN}http://${SERVER_IP}:${DASH_PORT}${NC}"
echo ""
echo -e "  ขั้นตอนถัดไป:"
echo -e "  1. เข้า ${CYAN}http://${SERVER_IP}:${DASH_PORT}/settings/${NC}"
echo -e "     → ตั้งค่า Wazuh Indexer URL และ Password"
echo -e "     → ตั้งค่า LINE, SMTP, TheHive และ integration อื่นๆ"
echo -e "  2. เข้า ${CYAN}http://${SERVER_IP}:${DASH_PORT}/license/${NC}"
echo -e "     → ใส่ License Key"
if [[ "${_THANS,,}" == "y" ]]; then
echo -e "  3. TheHive: ${CYAN}http://${SERVER_IP}:9000${NC}"
echo -e "     → Default login: admin@thehive.local / secret"
echo -e "     → สร้าง API Key แล้วใส่ใน Settings → TheHive"
fi
if [[ "${_OLANS,,}" == "y" ]]; then
echo -e "  4. Ollama: ${CYAN}http://localhost:11434${NC}"
echo -e "     → pull model: ollama pull qwen2.5:7b"
echo -e "     → ตั้งค่า model ใน Settings → Ollama"
fi
echo ""
