# Generated by Django 6.0.2 on 2026-02-26 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thehive_case_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('New', 'New'), ('InProgress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='New', max_length=50)),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('thehive_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='alerts.alert')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
