# Generated by Django 5.2.12 on 2026-03-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('LINE', 'LINE Notify'), ('MOPH', 'MOPH Notify'), ('Slack', 'Slack'), ('Email', 'Email')], max_length=20),
        ),
    ]
